### ISSUE TITLE
pip version number

### ISSUE THREAD

**Issue by TMiguelT** [johnyf/astutils#1]
The current pip version of astutils is listed as 0.0.1, while the github version is listed as 0.0.2. However it seems that both were updated on the same day. Does the pip version number need to be changed?

**Comment by johnyf** [comment]
[Version 0.0.1](https://github.com/johnyf/astutils/releases/tag/v0.0.1) is signified by tag `v0.0.1` and released on PyPI. 89377cdc3c8b10d5c8ca461cc665f819536d1e4f bumps to version 0.0.2, for which development happens, and will be tagged as `v0.0.2` when released. The convention followed is to bump the version number after each release.

**Comment by TMiguelT** [comment]
Oh I see!
